### ISSUE TITLE
KeyError: 'x-tracker-pagination-total'

### ISSUE THREAD

**Issue by martyhu** [dcripplinger/pivotaltracker-clubhouse#3]
Noticed that this key seems to be missing in the header when I try to import. The other headers are there, just not this one - weirdly

Full stacktrace below:

```
Traceback (most recent call last):
  File "./pivotaltracker-clubhouse", line 102, in <module>
    _run()
  File "./pivotaltracker-clubhouse", line 15, in _run
    total = int(response.headers['x-tracker-pagination-total'])
  File "/Library/Python/2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-tracker-pagination-total'
```

**Comment by dcripplinger** [comment]
@martyhu The code isn't currently written with intent of importing it, just running it from the command line. If you'd like to submit a pull request for making it more versatile, that would be cool. Otherwise I'll have to put this on the backburner.

**Comment by ckinsey** [comment]
I think @martyhu meant importing stories.  I'm getting the same error via the command line.

**Comment by ledermann** [comment]
I had the same issue. Fix: Remove filter ` AND label:clubhouse` in this line:
https://github.com/dcripplinger/pivotaltracker-clubhouse/blob/master/pivotaltracker-clubhouse#L11
